spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?autoReconnect=true&useSSL=false
    username: root
    password: 199729
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  data:
    mongodb:
      host: localhost
      port: 27017
      database: cloud